name: Check formatting

on:
  pull_request:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up dune
        uses: ocaml-dune/setup-dune@v2

      - run: dune tool install ocamlformat
      - run: dune fmt
